turret_reticle_x:
  .byte $6d, $6d, $6d, $6d, $6e, $6f, $6f, $70, $71, $73, $74, $75, $77, $78, $7a, $7c, $7d, $7f, $81, $82, $84, $85, $86, $88, $89, $8a, $8a, $8b, $8c, $8c, $8c, $8d
turret_reticle_y:
  .byte $b4, $b2, $b0, $af, $ad, $ac, $aa, $a9, $a8, $a7, $a6, $a5, $a4, $a4, $a4, $a4, $a4, $a4, $a4, $a4, $a5, $a6, $a7, $a8, $a9, $aa, $ac, $ad, $af, $b0, $b2, $b4

shot_anim_frames_0:
  .byte $b0, $b0, $b0, $b0, $b0, $b0, $b0, $b0
shot_anim_frames_1:
  .byte $b0, $b9, $b0, $b0, $b9, $b0, $b0, $b9
shot_anim_frames_2:
  .byte $b0, $b9, $b9, $b0, $b9, $b0, $b9, $b9
shot_anim_frames_3:
  .byte $b9, $a9, $b9, $b9, $b9, $b9, $b9, $b0
shot_anim_frames_4:
  .byte $b9, $b9, $a9, $ba, $b9, $b9, $b9, $a9
shot_anim_frames_5:
  .byte $ba, $b9, $aa, $b9, $ba, $a9, $b9, $aa
shot_anim_frames_6:
  .byte $a9, $ba, $aa, $a9, $ba, $aa, $ba, $a9
shot_anim_frames_7:
  .byte $aa, $aa, $aa, $ba, $aa, $aa, $ba, $aa
shot_anim_frames_8:
  .byte $aa, $aa, $ab, $aa, $aa, $aa, $aa, $aa
shot_anim_frames_9:
  .byte $ab, $aa, $aa, $ab, $9a, $aa, $ab, $aa
shot_anim_frames_10:
  .byte $ab, $9a, $ab, $9a, $ab, $9a, $ab, $aa
shot_anim_frames_11:
  .byte $9b, $9a, $ab, $9b, $9a, $9b, $ab, $9a
shot_anim_frames_12:
  .byte $9a, $9b, $9b, $9b, $9b, $9a, $9b, $9b
shot_anim_frames_13:
  .byte $0b, $9b, $9b, $9b, $0b, $9a, $9b, $9b
shot_anim_frames_14:
  .byte $0b, $9b, $0b, $9b, $0b, $9b, $0b, $9b
shot_anim_frames_15:
  .byte $0b, $9b, $0b, $0b, $0b, $0b, $0b, $9b
shot_anim_frames_16:
  .byte $0b, $1b, $0b, $0b, $0b, $0b, $0b, $1b
shot_anim_frames_17:
  .byte $0b, $1b, $0b, $1b, $0b, $1b, $0b, $1b
shot_anim_frames_18:
  .byte $0b, $1b, $1b, $1b, $0b, $1a, $1b, $1b
shot_anim_frames_19:
  .byte $1a, $1b, $1b, $1b, $1b, $1a, $1b, $1b
shot_anim_frames_20:
  .byte $1b, $1a, $2b, $1b, $1a, $1b, $2b, $1a
shot_anim_frames_21:
  .byte $2b, $1a, $2b, $1a, $2b, $1a, $2b, $2a
shot_anim_frames_22:
  .byte $2b, $2a, $2a, $2b, $1a, $2a, $2b, $2a
shot_anim_frames_23:
  .byte $2a, $2a, $2b, $2a, $2a, $2a, $2a, $2a
shot_anim_frames_24:
  .byte $2a, $2a, $2a, $3a, $2a, $2a, $3a, $2a
shot_anim_frames_25:
  .byte $29, $3a, $2a, $29, $3a, $2a, $3a, $29
shot_anim_frames_26:
  .byte $3a, $39, $2a, $39, $3a, $29, $39, $2a
shot_anim_frames_27:
  .byte $39, $39, $29, $3a, $39, $39, $39, $29
shot_anim_frames_28:
  .byte $39, $29, $39, $39, $39, $39, $39, $30
shot_anim_frames_29:
  .byte $30, $39, $39, $30, $39, $30, $39, $39
shot_anim_frames_30:
  .byte $30, $39, $30, $30, $39, $30, $30, $39
shot_anim_frames_31:
  .byte $30, $30, $30, $30, $30, $30, $30, $30
