turret_reticle_x:
  turret_reticle_x_0:
    .byte $6d
  turret_reticle_x_1:
    .byte $6d
  turret_reticle_x_2:
    .byte $6d
  turret_reticle_x_3:
    .byte $6d
  turret_reticle_x_4:
    .byte $6e
  turret_reticle_x_5:
    .byte $6f
  turret_reticle_x_6:
    .byte $6f
  turret_reticle_x_7:
    .byte $70
  turret_reticle_x_8:
    .byte $71
  turret_reticle_x_9:
    .byte $73
  turret_reticle_x_10:
    .byte $74
  turret_reticle_x_11:
    .byte $75
  turret_reticle_x_12:
    .byte $77
  turret_reticle_x_13:
    .byte $78
  turret_reticle_x_14:
    .byte $7a
  turret_reticle_x_15:
    .byte $7c
  turret_reticle_x_16:
    .byte $7d
  turret_reticle_x_17:
    .byte $7f
  turret_reticle_x_18:
    .byte $81
  turret_reticle_x_19:
    .byte $82
  turret_reticle_x_20:
    .byte $84
  turret_reticle_x_21:
    .byte $85
  turret_reticle_x_22:
    .byte $86
  turret_reticle_x_23:
    .byte $88
  turret_reticle_x_24:
    .byte $89
  turret_reticle_x_25:
    .byte $8a
  turret_reticle_x_26:
    .byte $8a
  turret_reticle_x_27:
    .byte $8b
  turret_reticle_x_28:
    .byte $8c
  turret_reticle_x_29:
    .byte $8c
  turret_reticle_x_30:
    .byte $8c
  turret_reticle_x_31:
    .byte $8d
turret_reticle_y:
  turret_reticle_y_0:
    .byte $b4
  turret_reticle_y_1:
    .byte $b2
  turret_reticle_y_2:
    .byte $b0
  turret_reticle_y_3:
    .byte $af
  turret_reticle_y_4:
    .byte $ad
  turret_reticle_y_5:
    .byte $ac
  turret_reticle_y_6:
    .byte $aa
  turret_reticle_y_7:
    .byte $a9
  turret_reticle_y_8:
    .byte $a8
  turret_reticle_y_9:
    .byte $a7
  turret_reticle_y_10:
    .byte $a6
  turret_reticle_y_11:
    .byte $a5
  turret_reticle_y_12:
    .byte $a4
  turret_reticle_y_13:
    .byte $a4
  turret_reticle_y_14:
    .byte $a4
  turret_reticle_y_15:
    .byte $a4
  turret_reticle_y_16:
    .byte $a4
  turret_reticle_y_17:
    .byte $a4
  turret_reticle_y_18:
    .byte $a4
  turret_reticle_y_19:
    .byte $a4
  turret_reticle_y_20:
    .byte $a5
  turret_reticle_y_21:
    .byte $a6
  turret_reticle_y_22:
    .byte $a7
  turret_reticle_y_23:
    .byte $a8
  turret_reticle_y_24:
    .byte $a9
  turret_reticle_y_25:
    .byte $aa
  turret_reticle_y_26:
    .byte $ac
  turret_reticle_y_27:
    .byte $ad
  turret_reticle_y_28:
    .byte $af
  turret_reticle_y_29:
    .byte $b0
  turret_reticle_y_30:
    .byte $b2
  turret_reticle_y_31:
    .byte $b4
